"""Add shipment_id to Shipment table

Revision ID: 27a20546eab3
Revises: d40fd422148e
Create Date: 2025-07-05 11:32:17.353435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a20546eab3'
down_revision: Union[str, Sequence[str], None] = 'd40fd422148e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('shipment_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'shipments', ['shipment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipments', type_='unique')
    op.drop_column('shipments', 'shipment_id')
    # ### end Alembic commands ###
