"""add display_name and tracking_url to shipping_providers

Revision ID: 4081a0e1d7dc
Revises: 822bcc7be82e
Create Date: 2025-07-10 10:40:57.527668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4081a0e1d7dc'
down_revision: Union[str, Sequence[str], None] = '822bcc7be82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
