"""Add display_name and tracking_url to shipping_providers

Revision ID: 822bcc7be82e
Revises: a2d7b3aabe87
Create Date: 2025-07-10 10:36:44.127434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '822bcc7be82e'
down_revision: Union[str, Sequence[str], None] = 'a2d7b3aabe87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping_providers', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('shipping_providers', sa.Column('tracking_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipping_providers', 'tracking_url')
    op.drop_column('shipping_providers', 'display_name')
    # ### end Alembic commands ###
