"""Add created_by to shipping_providers

Revision ID: 95813dc1167b
Revises: e7b98c00a5b5
Create Date: 2025-07-04 20:58:40.671257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95813dc1167b'
down_revision: Union[str, Sequence[str], None] = 'e7b98c00a5b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping_providers', sa.Column('created_by', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'shipping_providers', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipping_providers', type_='foreignkey')
    op.drop_column('shipping_providers', 'created_by')
    # ### end Alembic commands ###
