"""Enhanced Shipment model

Revision ID: d40fd422148e
Revises: 95813dc1167b
Create Date: 2025-07-05 11:18:44.305218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40fd422148e'
down_revision: Union[str, Sequence[str], None] = '95813dc1167b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('estimated_delivery', sa.DateTime(), nullable=True))
    op.add_column('shipments', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('shipments', sa.Column('dimensions', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('description', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'shipments', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.drop_column('shipments', 'created_by')
    op.drop_column('shipments', 'description')
    op.drop_column('shipments', 'dimensions')
    op.drop_column('shipments', 'weight_kg')
    op.drop_column('shipments', 'estimated_delivery')
    # ### end Alembic commands ###
